services:
  - type: web
    name: testik
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn testik.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4